---
- name: Ansible RBAC Playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/enterprise-rbac.yml

  tasks:
    - name: "Create org"
      ansible.platform.organization:
        name: "{{ rbac_config.organization.name }}"
        description: "{{ rbac_config.organization.description }}"
        aap_hostname: "{{ host }}"
        aap_token: "{{ oauth_token }}"
        aap_validate_certs: "{{ verify_ssl }}"
