---
- name: Ansible RBAC Playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/enterprise-rbac.yml

  tasks:
    - name: "Create org"
      ansible.platform.organization:
        name: "{{ rbac_config.organization.name }}"
        description: "{{ rbac_config.organization.description }}"
        gateway_hostname: "{{ lookup('env','CONTROLLER_HOST') }}"
        gateway_token: "{{ lookup('env','CONTROLLER_OAUTH_TOKEN') }}"
        validate_certs: false
