---
- name: Ansible RBAC Playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/enterprise-rbac.yml

  tasks:
    - name: "Create org"
      ansible.platform.organization:
        name: "{{ rbac_config.organization.name }}"
        description: "{{ rbac_config.organization.description }}"
        aap_hostname: "{{ lookup('env','CONTROLLER_HOST') }}"
        aap_token: "{{ lookup('env','CONTROLLER_OAUTH_TOKEN') }}"
        aap_validate_certs: "{{ lookup('env','CONTROLLER_VERIFY_SSL') | default(true) | bool }}"
